name: PlayersInCubes
main: me.asofold.bukkit.pic.PlayersInCubes
version: 1.2.1

commands:
  playersincubes:
    description: 'Manage PlayersInCubes.'
    usage: '/playersincubes ...: reload | info | cleanup | disable | enable | stats | stats reset | Aliases: pic, pcubes'
    aliases:
    - pic
    - pcubes
