name: PlayersInCubes
main: me.asofold.bukkit.pic.PlayersInCubes
version: 0.0.0

commands:
  playersincubes:
    description: 'Manage PlayersInCubes.'
    usage: '/pcubes ...: reload |'
    aliases:
    - pic
    - pcubes
