name: PlayersInCubes
main: me.asofold.bpl.pic.PlayersInCubes
version: 2.2.13

commands:
  playersincubes:
    description: 'Manage PlayersInCubes.'
    usage: '/playersincubes ...: reload | info | cleanup | disable | enable | stats | stats reset | Aliases: pic, pcubes'
    aliases:
    - pic
    - pcubes
