name: PlayersInCubes
main: me.asofold.bukkit.pic.PlayersInCubes
version: 1.0.0

commands:
  playersincubes:
    description: 'Manage PlayersInCubes.'
    usage: '/pcubes ...: reload | enable | disable | stats | stats reset |'
    aliases:
    - pic
    - pcubes
