name: PlayersInCubes
main: me.asofold.bukkit.pic.PlayersInCubes
version: 1.0.0

commands:
  playersincubes:
    description: 'Manage PlayersInCubes.'
    usage: '/playersincubes ...: reload | disable | enable | cleanup | stats | stats reset | ignore | ignore <player> | cleanup | Aliases: pic, pcubes'
    aliases:
    - pic
    - pcubes
